name: Crowdin Integration Tools
description: A collection of tools to manage freeCodeCamp's integrations with Crowdin
author: freeCodeCamp
branding:
  icon: activity
  color: blue
runs:
  using: node20
  main: dist/index.js
env:
  # These are required for the action to run.
  CROWDIN_PERSONAL_TOKEN:
    description: API token for Crowdin.
    required: true
  CROWDIN_API_URL:
    description: API URL for Crowdin.
    required: true
  CROWDIN_PROJECT_ID:
    description: ID for the project on Crowdin.
    required: true
  PLUGIN:
    description: Name of the plugin/module to run.
    required: true
  # These are used for hiding and unhiding specific strings.
  FILE_NAME:
    description: The name of the file where the string is found.
    required: true
  STRING_CONTENT:
    description: The content of the string.
    required: true
  # This is used for deleting files from Crowdin, or for converting the chinese files.
  FILE_PATH:
    description: Relative path for files to recursively handle.
    required: true
  # These are all used for the commit plugin.
  GH_USERNAME:
    description: The username of the GitHub account to commit from.
    required: true
  GH_EMAIL:
    description: The email of the GitHub account to commit from.
    required: true
  GH_BRANCH:
    description: The branch to commit to.
    required: true
  GH_MESSAGE:
    description: The message to use when generating the commit.
    required: true
  # These are used in the pull request plugin.
  GH_TOKEN:
    description: "PAT with write access to create PRs"
    required: true
  BRANCH:
    description: "Branch name to which commits are made"
    required: true
  REPOSITORY:
    description: "owner and repo name specified as ownerName/repoName"
    required: true
  BASE:
    description: "base branch name"
    default: "main"
    required: false
  TITLE:
    description: "PR title"
    required: true
  BODY:
    description: "PR body text"
    required: true
  LABELS:
    description: "PR labels, comma-separated"
    required: false
  REVIEWERS:
    description: "Requested PR reviewers, comma-separated"
    required: false
  TEAM_REVIEWERS:
    # Note that this should be a slug, not a full tag
    # So a requested review from @freeCodeCamp/dev-team
    # Should be passed only as 'dev-team'
    description: "Requested organization team PR reviewers"
    required: false
