"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path_env": "CROWDIN_BASE_PATH"
"base_url_env": "CROWDIN_BASE_URL"

"preserve_hierarchy": true

files:
  [
    {
      "source": "/apps/client/i18n/locales/english/intro.json",
      "translation": "/apps/client/i18n/locales/%language%/%original_file_name%",
    },
    {
      "source": "/apps/client/i18n/locales/english/translations.json",
      "translation": "/apps/client/i18n/locales/%language%/%original_file_name%",
    },
  ]
