"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path_env": "CROWDIN_BASE_PATH"
"base_url_env": "CROWDIN_BASE_URL"

"preserve_hierarchy": true

files:
  [
    {
      "source": "/mobile-app/lib/l10n/app_en.arb",
      "translation": "/mobile-app/lib/l10n/app_%two_letters_code%.arb",
    },
  ]
