name: Generate Distribution Build
on:
  push:
    branches:
      - main

jobs:
  build-dist:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Distribution Package
        run: npm run package

      - name: Commit Build
        run: |
          git add dist
          git commit -m "chore: build action"
          git push

